require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'fletex_app' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # PERMISSIONS PODS
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera"
  pod 'Permission-LocationWhenInUse', :path => "../node_modules/react-native-permissions/ios/LocationWhenInUse"
  pod 'Permission-LocationAlways', :path => "../node_modules/react-native-permissions/ios/LocationAlways"
  pod 'Permission-PhotoLibrary', :path => "../node_modules/react-native-permissions/ios/PhotoLibrary"
  pod 'Permission-MediaLibrary', :path => "../node_modules/react-native-permissions/ios/MediaLibrary"
  pod 'Permission-Microphone', :path => "../node_modules/react-native-permissions/ios/Microphone"
  # END PERMISSIONS PODS

  
  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'fletex_appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'fletex_app-tvOS' do
  # Pods for fletex_app-tvOS

  target 'fletex_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
